### ISSUE TITLE
Audio to Text

### ISSUE THREAD

**Issue by tbrand** [aws-samples/generative-ai-use-cases-jp#103]
Kendra と同様に生成 AI とは別のツールとして追加

**Comment by okamoto-aws** [comment]
ご対応いただきありがとうございます！！
PR #124 のスコープがわかっていないのですが、生成系AIのユースケースとしては下記ができるとうれしいと思いました。今後の実装で作っていくでもありなのかもしれません。
- ファイルアップロード→同期で結果取得、はUXがよくないため、非同期でジョブ結果が見れるとうれしい
  - Transcribeのラッパーみたいになっちゃって微妙ですかね
- 取得した書き起こしに対して質問をしたい
  - 書き起こし結果画面にinput formをつけて「質問」を投げられるとか
  - 書き起こし後、要約を自動実行するとか
- 話者識別をデフォルト設定、またはオプションでオンできるとLLM的には使いやすい
- LLMへの入力時に、正しく認識してほしい固有名詞集をつけるUIがあると、ユースケースの効果がデモしやすくてよい
