### ISSUE TITLE
RAG チャットのリンクを生成ではなく実際の url にしたい

### ISSUE THREAD

**Issue by nakayukl-demo** [aws-samples/generative-ai-use-cases-jp#131]
課題：現在、RAG チャットの参考ドキュメントは文字列を生成している実装です。webクローラした結果の url ではないため、リンクをクリックしても存在しない、という事象が発生しています。

要望：retrieve api にて kendra index から候補テキストを抜粋した際に、一緒に元の url を取得して、それを表示するように変更することは可能でしょうか？

**Comment by nakayukl-demo** [comment]
こちらもし、元の[DocumentURI](https://docs.aws.amazon.com/kendra/latest/APIReference/API_RetrieveResultItem.html#kendra-Type-RetrieveResultItem-DocumentURI) が大量になってしまい、LLM が生成した回答テキストに合致しないものも含まれてしまう、といった課題について議論した結果、など、既存の議論結果などあればコメントいただければ幸いです。

**Comment by maekawataiki** [comment]
こちらの件、修正されました。

**Comment by nakayukl-demo** [comment]
おぉぉぉ、ありがとうございます！！！！！
