### ISSUE TITLE
画像生成改善案

### ISSUE THREAD

**Issue by tbrand** [aws-samples/generative-ai-use-cases-jp#134]
- [x] チャットの自動スクロール
- [ ] #182

**Comment by wadabee** [comment]
* クリア時に画像1枚目を選択する
* デモから遷移 -> 画像生成 -> 違う画面へ遷移 -> 画像生成画面に戻ってくる -> 画像生成処理が勝手に動く
* 初期画像を適当に設定 -> 初期画像を再度開いて背景色を変えようとして変わらない（画像の背景色が透過されていないため）

**Comment by maekawataiki** [comment]
別画面（チャット履歴など）に遷移してから戻ってくると履歴が消えて新規チャットになる。クリアで初期化はされるので別画面が見たくなって（過去の履歴の確認など）戻ってきた際はリセットされずに履歴が残っていて続きから生成できると嬉しい。

**Comment by tbrand** [comment]
すべて子 issue として作成してもらったので close
