### ISSUE TITLE
機能変更時の取り込み手順があると嬉しいです

### ISSUE THREAD

**Issue by nakayukl-demo** [aws-samples/generative-ai-use-cases-jp#137]
コントリビューションが増加し、ユースケースも増えています。特に画像生成のユースケースは素晴らしいと思います。すでに構築済みの状態から、新しい機能を取り込む手順があると、追いつきが簡単となり嬉しいです。

**Comment by tbrand** [comment]
:+1:

**Comment by tbrand** [comment]
ユースケースの追加方法について、こちらのブログで詳細に解説し、またこのブログへのリンクを README.md に追加しました。https://aws.amazon.com/jp/builders-flash/202311/bedrock-interpreter/#04
