### ISSUE TITLE
cdk destroy時にdeleteが失敗・スキップされるリソースがある

### ISSUE THREAD

**Issue by gentksb** [aws-samples/generative-ai-use-cases-jp#156]
## 事象

デプロイしたスタックに対して `cdk destroy` を実行する際に下記のリソースがDELETE_FAILEDもしくはDELETE_SKIPPEDとなる

- ログ用S3バケット(ApiWebS3LoggingBucketxxxxx)
- DynamoDBテーブル
- Cognitoユーザープール
- APIGW CloudwatchRole

## 対応案

各リソースの `RemovalPolicy`, `cloudWatchRoleRemovalPolicy` を DESTROYに設定、S3バケットは`loggingBucketProps` にも `autoDeleteObject: true` を設定する

### 対象

packages/cdk/lib/construct/database.ts
packages/cdk/lib/construct/auth.ts
packages/cdk/lib/construct/web.ts

## その他

AWS::ApiGateway::Account もSKIPPEDになっていますが、ロールを消したら消える気がしています

**Comment by tbrand** [comment]
ありがとうございます。こちら全てのリソースに RemovalPolicy=DESTROY を設定いたしました。
