### ISSUE TITLE
デプロイ後のリソース消去方法について

### ISSUE THREAD

**Issue by Kenkentake** [aws-samples/generative-ai-use-cases-jp#157]
デプロイ後にリソースを消去する方法をREADMEに記載頂くと私のような初心者の助けになると感じました。ご検討お願い致します。既に記述済みで私が見過ごしていましたらご放念ください。
改めて大変有益なコードを公開していただきありがとうございます。

**Comment by tbrand** [comment]
ありがとうございます。こちらドキュメントにて対応させていただきました。

**Comment by Kenkentake** [comment]
早速のご対応ありがとうございました！
