### ISSUE TITLE
ImageToTextのユースケース追加

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#198]
商品画像を読み込むと商品説明を自動作成するようなものを想定。

以下のAWSブログで紹介されている内容が参考になりそう。
https://aws.amazon.com/jp/blogs/machine-learning/automating-product-description-generation-with-amazon-bedrock/

**Comment by maekawataiki** [comment]
Claude 3 対応で Image to Text が対応したため Close します。
