### ISSUE TITLE
【機能追加要望】Bedrock Knowledge baseとの連携機能

### ISSUE THREAD

**Issue by tsukumonasu** [aws-samples/generative-ai-use-cases-jp#226]
Kendraも非常に有用でしたが、高価なため。

**Comment by maekawataiki** [comment]
#308 で Agent for Bedrock に対応したため、Knowledge Base と連携した Agent を作成して登録することで連携できるようになりました。
以下の手順で Knowledge Base を Agent に連携することができます。
https://docs.aws.amazon.com/ja_jp/bedrock/latest/userguide/knowledge-base-add.html
