### ISSUE TITLE
チャットのURLパラメータでシステムコンテキスト/プロンプト/使用モデルを指定する

### ISSUE THREAD

**Issue by okamoto-aws** [aws-samples/generative-ai-use-cases-jp#289]
パラメータに直接システムコンテキスト/プロンプト/使用モデルの情報を含ませることで、ブラウザブックマーク等でユースケースを保持したり、Greasemonkey, ブラウザ拡張等外部からプロンプトを注入できるようにしたい。
サーバーサイドでカスタムシステムコンテキストを保持する機能とは別で考えたい。
チャット画面にユースケースをふくむURLをコピーできるボタンがあるとなお良し(履歴がある場合にどこまで保持するか難しそうなので一旦棚上げ)。

**Comment by tbrand** [comment]
対応しました！
