### ISSUE TITLE
[質問] クエリパラメータを利用することはできますか？

### ISSUE THREAD

**Issue by ysekiy** [aws-samples/generative-ai-use-cases-jp#319]
こんにちは、素晴らしいリポジトリをありがとうございます。
ターミナルを使う中で、コマンドが分からない事があるという背景から、`.zshrc`に下記のようなエイリアスを設定してます。

``` 
# google 検索
google() { open /Applications/Google\ Chrome.app/ "http://www.google.com/search?q=$1"; }
alias g="google"

# chatgpt
chatgpt() { open /Applications/Google\ Chrome.app/ "https://chat.openai.com/?model=gpt-4&q=$1"; }
alias c="chatgpt"
```

こうすることで、開発の中で分からない物があったとき、

`g lambdaを作るコマンド`や`c lambdaを作るコマンドを教えて` とターミナル上で打つとシームレスに検索や生成AIへの問い合わせが可能になっています。claudeにシームレスに聞けるとどんな体験になるのか試してみたいのですが、すでにこのサンプルで`?query=hogehoge`や`?q=hogehoge`といったクエリパラメータを利用することはできるのでしょうか？

**Comment by tbrand** [comment]
フィードバックありがとうございます！とても興味深い使い方で参考になります！

こちらの Issue のような使い方という認識であっていますでしょうか？
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/289

クエリパラメータについては複数のフィードバックいただいておりますので、積極的に実装を進めていきたいと思います！:bow:

**Comment by ysekiy** [comment]
重複するissueがあったんですね。失礼しました。認識同じです。

update楽しみにしています。

**Comment by tbrand** [comment]
対応しました！

**Comment by ysekiy** [comment]
ありがとうございます。

```
XXX.cloudfront.net/chat?content=hogehoge
```

ですね。動作いい感じです。
