### ISSUE TITLE
Amazon SageMakerのカスタムモデルを利用したい場合

### ISSUE THREAD

**Issue by michinori-k** [aws-samples/generative-ai-use-cases-jp#352]
以下の箇所に記載されたSageMakerエンドポイントを利用する機能が動作しません。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/DEPLOY_OPTION.md#amazon-sagemaker-%E3%81%AE%E3%82%AB%E3%82%B9%E3%82%BF%E3%83%A0%E3%83%A2%E3%83%87%E3%83%AB%E3%82%92%E5%88%A9%E7%94%A8%E3%81%97%E3%81%9F%E3%81%84%E5%A0%B4%E5%90%88

「ELYZA-japanese-Llama-2-7b-instruc」を利用するパターンとしてcdk.jsonを編集してデプロイしていますが、
チャット画面のモデル一覧プルダウンにELYZAが表示されません。
こちらの機能を有効にするにはどうすれば良いでしょうか。

宜しくお願い致します。

**Comment by maekawataiki** [comment]
ドロップダウンに SageMaker エンドポイントが反映されない不具合があったため修正しました。

最新版をダウンロードし、`cdk.json` の `endpointNames` に追加したエンドポイント名が表示されるようになっているはずです。

**Comment by michinori-k** [comment]
ありがとうございます。
SageMakerのエンドポイントがチャット画面のモデルから選択できるようになっていることを確認出来ました。

追加でご教示頂きたいのですが、
RAGチャットだとSageMakerエンドポイントを選択してチャット入力をした場合に回答が表示されません。
これは仕様でしょうか？

**Comment by maekawataiki** [comment]
手元の環境でログを確認しましたが、RAG の入力トークン数が大きい（手元の検証では 3200 トークン前後）のが問題でした。
Elyza のモデルは 4096 トークンまでしか扱えず、TGI でデプロイする際に `'MAX_INPUT_LENGTH': "2048"` を設定しているのではないかと思います。
RAG では Kendra の [Retrieval API](https://docs.aws.amazon.com/kendra/latest/APIReference/API_Retrieve.html) を使用しておりデフォルトでは 10 件出力するので入力トークンが大きくなる傾向があります。

対策としては Retrieve API の PageSize を減らす、入力トークンの大きいモデルを使うなどが挙げられます。

Retrieval API の PageSize を変更するには [retrieveKendra.ts](https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/cdk/lambda/retrieveKendra.ts#L46) で `PageSize: 5` などを設定すると検索結果の数を絞ることができます。

入力トークンの大きいモデルとしては Anthropic Claude やカスタマイズ可能な OSS モデルであれば [CALM2](https://aws.amazon.com/jp/blogs/news/cyberagentlm2-on-sagemaker-jumpstart/) などがあります。
