### ISSUE TITLE
ファイルの個別Upload機能

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#356]
### ◆背景・目的
- 個人で保管しているファイルをUploadしてそのファイル内に記載されている内容に関して問い合わせたいケースがある。例えば契約書のチェックであったり、アンケート結果を取りまとめたEXCEL表であったりです。

### ◆改善要望内容
本家Claudeでは、文書ファイルか画像であればUploadして回答を得られるような機能が実装されていますが、
同様の機能をご検討して頂けると幸いです。
・1ファイルの最大サイズ：100MB程度
・同時にUpload可能なファイル数：30ファイル程度

![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/95996519/8f062446-026b-4363-9c4a-d4e1dbd9e2b3)

### ◆Upload機能でサポートしてほしいファイル形式
　1. PDF・WORD・TEXTファイル：契約書のチェックや文書の構成、英文文書の翻訳依頼など
　　※可能であれば、DocuWorks文書（*.xdw）も。
　2. EXCELファイル：アンケート結果EXCELの分析やマクロファイルの解析など
　3. PowerPoint：文章校正や日本語文書の英訳依頼など
　4. CSV：大容量ログファイルの解析など
　5. 画像ファイル：部品の説明（該当部品に関する社内ドキュメントとの連携、交換方法など）
　6. Outlookメール形式（msg形式）：複数のメールファイルを集約して要約させる、など
　7. 主要CAD図面ファイル
　8. htmlファイル：マニュアルがhtml形式になっているケースなど

**Comment by tbrand** [comment]
こちら全てのファイルフォーマットではありませんが、基本的なものはサポートされていると思いますので、一旦クローズさせていただきます。業務要件上、必要なファイルフォーマットで未対応なものがあれば改めて別 Issue を立てていただければと思います。
