### ISSUE TITLE
アップロードできない画像がある

### ISSUE THREAD

**Issue by kazuhitogo** [aws-samples/generative-ai-use-cases-jp#366]
ファイル名に日本語が含まれているとアップロードできない可能性。
図１.png がアップロードできませんでした。

**Comment by okamoto-aws** [comment]
これ試しましたが再現せず、既に解決済みですかね？

**Comment by kazuhitogo** [comment]
別の問題っぽかったのでクローズしちゃいます！（おそらくアップロード中にSubmitボタンが活性化されてしまっていた問題)
