### ISSUE TITLE
小さい画像の認識精度

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#373]
小さい画像の場合、認識率がいまいちです。何らかの改善策はないでしょうか？
おそらくPowerPointなどに貼っている画像を処理する場合、小さい画像程度のサイズしかありません。

- 小さい画像
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/95996519/7a9931f6-5051-45c9-9af1-e3ca12b67aaf)

>この画像には、黄色い三角形の注意標識が描かれています。標識の中央には犬の顔の絵が大きく描かれており、その周りに赤い縁取りがあります。標識の上部には大きな文字で"DRILL"と書かれています。

>この標識は、おそらく掘削作業や建設現場などで使用されるものだと思われます。犬の絵は、作業中に犬に気をつけるよう警告する意味があるでしょう。つまり、この標識は作業員に対し、掘削中は周りに犬がいる可能性があり、注意が必要であることを伝えているのだと推測されます。

- 大きい画像
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/95996519/e8dbac16-607f-4cc9-a37a-095586a1cc72)

>この画像は、おそらくアルバムのCDジャケットやレコードのジャケットを示しているものと思われます。中央に大きく「DRILL」と書かれた赤と緑の菱形の標識があり、その中に犬の絵が描かれています。標識の下に「ANTHOLOGY」という単語が書かれています。

>左側には日本語の文字が縦書きで書かれており、アーティスト名やアルバム名、曲名のリストが記載されていると推測されます。右上には「Ki oon」という文字があり、おそらくレーベル名または制作会社名を表していると考えられます。したがって、この画像はおそらく音楽アルバムのジャケットデザインで、中央の犬の絵と「DRILL」の文字がアルバムのタイトルやアーティスト名を象徴していると推測されます。

**Comment by xtc-izou** [comment]
300 x 300ピクセル程度だと厳しそうです。

**Comment by okamoto-aws** [comment]
https://docs.anthropic.com/claude/docs/vision#image-best-practices
上記Anthropicの公式ドキュメントをご確認ください。良い結果を得るためにはある程度の画像品質が必要そうです。

**Comment by xtc-izou** [comment]
ありがとうございます！
画像をUploadする際にはベストプラクティスに沿った形でUploadするようにします。
