### ISSUE TITLE
メニュー表示の改善

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#375]
### ◆改善要望
左側のメニュー表示に関しての改善要望です。ログイン後、最初はユースケースが
すべて表示されており、「ツール」「会話履歴」「リンク」は畳まれている状態で
表示して頂きたいです。スマホでも同様の表示にしていただきたいです。

理由は利用したいユースケースの表示が切れている場合、毎回スクロールするのが
手間なので最初はすべてのユースケースを表示して頂けると手間が省けると考えています。

（ログイン後、ユースケースの一覧が切れてしまっている）
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/95996519/e889c1ce-437d-440a-b0f1-1cb057c506ec)

外部ディスプレイを接続している時は気づかなかったのですが、
ノートPCのディスプレイで表示させた場合、気になりました。

**Comment by tbrand** [comment]
ありがとうございます！こちらメニュー開閉の状態をブラウザに保存するようにして対応いたしました！よろしくお願いいたします！
