### ISSUE TITLE
RAGチャット（Kendra）で画像Upload機能の実装

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#376]
### ◆改善要望
- KendraでのRAGチャットでも画像のUpload機能を実装していただきたいです。
- 故障部品などの写真をスマホで撮影し、その部品の交換方法などをKendraから関連文書として検索できたら、有益な使い方になると考えています。

**Comment by tbrand** [comment]
ありがとうございます！こちらメニュー開閉の状態をブラウザに保存するようにして対応いたしました！よろしくお願いいたします！
