### ISSUE TITLE
クリップボード内の画像キャプチャの貼り付け機能

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#377]
### ◆改善要望
- 画面キャプチャ（スクリーンショット）をファイルとして一旦保存するのではなく、そのままコピペで貼り付けられると、エラー画面などを調査する際に便利だと思いました。

**Comment by wadabee** [comment]
こちらについては、#383 のPRでマージしました！
Issueはクローズさせていただきます。
