### ISSUE TITLE
cognitoのloginをgoogle認証に対応させたい

### ISSUE THREAD

**Issue by tetuya-iyell** [aws-samples/generative-ai-use-cases-jp#399]
お世話になっております

generative-ai-use-cases-jp を活用させていただいております
webのloginをgoogle認証に対応をさせるにはどのようにすればよいでしょうか

cognito側の設定については、Google認証に対応させるように手動で設定変更をおこないました
また、AuthWithUserpool.tsxを以下の通りのコードにしてみたのですが、ログイン画面にGoogle認証が表示されませんでした

これは、どのようにすればログイン画面でGoogle認証が利用できるようになるでしょうか
ご教授いただけますと幸いです

よろしくお願い申し上げます

```
import { Amplify, I18n } from 'aws-amplify';
import { Authenticator, translations } from '@aws-amplify/ui-react';
import App from '../App.tsx';

const selfSignUpEnabled: boolean =
  import.meta.env.VITE_APP_SELF_SIGN_UP_ENABLED === 'true';

const AuthWithUserpool: React.FC = () => {
  Amplify.configure({
    Auth: {
      userPoolId: import.meta.env.VITE_APP_USER_POOL_ID,
      userPoolWebClientId: import.meta.env.VITE_APP_USER_POOL_CLIENT_ID,
      identityPoolId: import.meta.env.VITE_APP_IDENTITY_POOL_ID,
      authenticationFlowType: 'USER_SRP_AUTH',
      oauth: {
        domain: 'https://hogehoge.auth.us-east-1.amazoncognito.com', // Cognito ドメインを設定
        scope: ['email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'http://localhost:3000/auth/sign_in', // リダイレクト URL を設定
        redirectSignOut: 'http://localhost:3000/', // リダイレクト URL を設定
        responseType: 'code',
        options: {
          // Google の設定
          GoogleWebClient: '388719245530-dnrb7i503eupup9fdtruhh0d511je0c7.apps.googleusercontent.com', // Google Web Client ID を設定
        },
      },
    },
  });

  I18n.putVocabularies(translations);
  I18n.setLanguage('ja');

  return (
    <Authenticator
      hideSignUp={!selfSignUpEnabled}
      federated={{
        google_client_id: 'hogehoge.apps.googleusercontent.com', // Google Web Client ID を設定
      }}
      components={{
        Header: () => (
          <div className="text-aws-font-color mb-5 mt-10 flex justify-center text-3xl">
            Generative AI Use Cases on AWS
          </div>
        ),
      }}
    >
      <App />
    </Authenticator>
  );
};

export default AuthWithUserpool;

```

**Comment by Sugi275** [comment]
ご連絡ありがとうございます！

「google認証に対応したい」の内容次第ですが、ソースコードの変更は必要がない可能性があります。
「google認証に対応したい」の詳細をお伺いさせていただいてもよろしいでしょうか？

以下の想定をもっておりますが、ご確認頂けますと幸いです。

・組織の中で Google Workspaces を利用していて、これと Generative AI Use Cases JP を連携したい
・世の中一般に Public に取得できる Google アカウントは連携対象ではない
   (例えば、私自身、個人の gmail アカウントを持っていますが、これはログインを許可するの対象ではない)

**Comment by Sugi275** [comment]
2 つのパターンで対応方法をお伝えしたいです。

■パターン 1 : Amplify UI の Authenticator socialProviders を指定するパターン
AuthWithUserpool.tsx を編集いただいていますが、編集内容に誤りがあるように見えています。
以下の URL に、`<Authenticator socialProviders={['amazon', 'apple', 'facebook', 'google']}>` という指定方法があり、こちらをお試しいただけると UI に表示される可能性があると思います。こちらお試しいただけますでしょうか？

https://ui.docs.amplify.aws/react/connected-components/authenticator/configuration#social-providers

Generative AI Use Cases JP では、Amplify UI の Authenticator コンポーネントを利用しており、この Document を参照いただけると幸いです。(おそらく参考にいただいたのは、古いコンポーネントの場合だったのかもしれません)
これで対応が出来たら、結果を共有いただけますと幸いです。

■パターン2 : SAML 認証で実施するパターン
Google Workspace は SAML 認証を提供している認識です。
つまり、以下の AuthWithSAML.tsx をそのままソースコードを変更せずに Google Workspace と連携ができる想定でいます。https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/web/src/components/AuthWithSAML.tsx

具体的な手順はこちらの方でも確認したいとは考えておりますが、少々お時間をいただくと思います。
以下の Document が Azure AD と SAML 連携を行う手順となっており、Google Workspace とうまく読み替えていけば、ソースコード変更せずに対応ができる可能性があります。 (もしパターン 1 が難しそうな場合は、こちらもトライいただけると幸いです。)
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/SAML_WITH_ENTRA_ID.md

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
齊藤です

早速のご教授、誠にありがとうございます
シンプルにAuthWithUserpool.tsxを元にコードに戻して
```
return (
    <Authenticator socialProviders={['google']}
      hideSignUp={!selfSignUpEnabled}
      federated={{
```
の様な形で、認証ができるか確認をおこないました

ログイン画面にはGoogle認証のページが表示をされるのですが、Google認証のボタンを押下しても先に進まず
ローディングが続く感じで先に進むことが出来ませんでした

もしかすると、cognitoのcallback urlの設定に誤りがあるのかもしれないのですが
cognitoでgoogle認証をするばあい、cludfrontのURLを設定すればよいのでしょうか

パターン1は上手くいかなかったので、引き続きパターン2の検証を進めたいと思います
進捗がありしだい共有をさせていただきます

引き続き、よろしくお願い申し上げます

**Comment by Sugi275** [comment]
パターン1 について、以下のような指定はいかがでしょう？
自信があるわけではないですが、現在齊藤様に指定いただいている `federated={{...` の部分は指定しなくてもよいのかなと感じた次第です。

```
    <Authenticator
      socialProviders={['google']}
      hideSignUp={!selfSignUpEnabled}
      components={{
        Header: () => (
          <div className="text-aws-font-color mb-5 mt-10 flex justify-center text-3xl">
            Generative AI Use Cases on AWS
          </div>
        ),
      }}>
      <App />
    </Authenticator>
```


> ログイン画面にはGoogle認証のページが表示をされるのですが、Google認証のボタンを押下しても先に進まず
ローディングが続く感じで先に進むことが出来ませんでした

これは気になりますね・・・。

> もしかすると、cognitoのcallback urlの設定に誤りがあるのかもしれないのですが
cognitoでgoogle認証をするばあい、cludfrontのURLを設定すればよいのでしょうか

こちらは、CloudFront の URL を設定する方法もよいですし、`http://localhost:5173` を指定しても良いと思います。両方指定できるので、2 つとも設定しておくとシンプルでよいでしょう。少なくとも Azure AD との連携では、`http://localhost:5173` を指定してローカル環境で動作確認が出来ました。

また、以下の Document で Google 側に必要な設定を載せていますので、こちらもご参考頂けますと幸いです。

https://docs.amplify.aws/javascript/build-a-backend/auth/add-social-provider/#set-up-your-social-auth-provider

パターン 1 や 2 で進捗がありましたら共有いただけますと幸いです。

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
齋藤です

ご教授、誠にありがとうございます
ご提供頂いた内容の通り、以下の様なコードに変更をしました
```
import { Amplify, I18n } from 'aws-amplify';
import { Authenticator, translations } from '@aws-amplify/ui-react';
import App from '../App.tsx';

const selfSignUpEnabled: boolean =
  import.meta.env.VITE_APP_SELF_SIGN_UP_ENABLED === 'true';

const AuthWithUserpool: React.FC = () => {
  Amplify.configure({
    Auth: {
      userPoolId: import.meta.env.VITE_APP_USER_POOL_ID,
      userPoolWebClientId: import.meta.env.VITE_APP_USER_POOL_CLIENT_ID,
      identityPoolId: import.meta.env.VITE_APP_IDENTITY_POOL_ID,
      authenticationFlowType: 'USER_SRP_AUTH',
      oauth: {
        domain: 'gen-ai-auth.auth.us-east-1.amazoncognito.com', // Cognito ドメインを設定
        scope: ['email', 'profile', 'openid', 'aws.cognito.signin.user.admin'],
        redirectSignIn: 'http://localhost:5173/', // リダイレクト URL を設定
        redirectSignOut: 'http://localhost:5173/', // リダイレクト URL を設定
        responseType: 'code',
        options: {
          // Google の設定
          GoogleWebClient: '388719245530-dnrb7i503eupup9fdtruhh0d511je0c7.apps.googleusercontent.com', // Google Web Client ID を設定
        },
      },
    },
  });

  I18n.putVocabularies(translations);
  I18n.setLanguage('ja');

  return (
    <Authenticator socialProviders={['google']}
      hideSignUp={!selfSignUpEnabled}
      components={{
        Header: () => (
          <div className="text-aws-font-color mb-5 mt-10 flex justify-center text-3xl">
            Generative AI Use Cases on AWS
          </div>
        ),
      }}>
      <App />
    </Authenticator>
  );
};

export default AuthWithUserpool;
```

また、cognito側のホストされたUIは以下の通りに変更をしました
```
許可されているコールバック URL
http://localhost:5173
https://d2fowk9sgynx98.cloudfront.net
許可されているサインアウト URL
http://localhost:5173
https://d2fowk9sgynx98.cloudfront.net
```

この状態でローカル開発環境からGoogle認証をクリックすると以下のURLに遷移し、そのごdefaultのログイン画面に戻ってくるという振る舞いになってしまっております

コード内の
```
        redirectSignIn: 'http://localhost:5173/', // リダイレクト URL を設定
        redirectSignOut: 'http://localhost:5173/', // リダイレクト URL を設定
```
を削除しても同様の振る舞いになりました
これは、cognitoとGoogle認証の設定に誤りがあるのでしょうか

ご教授いただけますと幸いです
よろしくお願い申し上げます

[google認証を押下したときに遷移するURL]
http://localhost:5173/?error_description=RedirectUri+is+not+registered+with+the+client+&state=cegnPHsrUVfF0JirK2ftD2yvDD5ug35o&error=invalid_request

**Comment by Sugi275** [comment]
ありがとうございます。過去ちょっと記憶にあるのが、末尾のスラッシュの件です。

React のソースコードでは以下のように指定しています。末尾にスラッシュを入れられていると思います。
```
        redirectSignIn: 'http://localhost:5173/', // リダイレクト URL を設定
        redirectSignOut: 'http://localhost:5173/', // リダイレクト URL を設定
```

一方、Cognito に登録されているのが、以下のようにスラッシュが入っていません。
```
許可されているコールバック URL
http://localhost:5173
https://d2fowk9sgynx98.cloudfront.net
許可されているサインアウト URL
http://localhost:5173
https://d2fowk9sgynx98.cloudfront.net
```

これは確か良くなかった記憶があります。末尾のスラッシュ無しでやってみていただくといかがでしょうか？
(場合によっては、AWS サポートへも問合せなど頂けるとスムーズな場面があるかもしれません。AWS 側の詳細を確認することが得意な AWS サポートの活用もおすすめです)

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
ご返信ありがとうございます

ご指摘のところは私も気になっていたので、末尾の「/」の有り無しで試してみたのですがGoogle認証を押下後、以下のURLに遷移しログイン画面に戻ってしましまいます
[URL]
http://localhost:5173/?code=1c5e0e32-97df-4d5a-b09b-4bb6699f0f07&state=BOOKaLD5wQNOg9p7OXRN9LRTzG8mvqZX

AWSサポートにも確認をしており、AWSサポート側ではcognito側の問題では無いと言う回答でした。念の為、http://localhost:5173でGoogle認証を行った際のharファイルを取得しcognito側で問題が無いか確認をいただく方向になりました

AWSサポートとしては、Google認証後のlogin処理(lamdaedge？)の問題では無いかと回答をされておりました
このあたりのご確認をいただくことは可能でしょうか

どうぞよろしくお願い申し上げます

**Comment by Sugi275** [comment]
共有もいただきありがとうございます！念のため AWS サポートの問合せ ID もいただいてよろしいでしょうか？

Google Workspace と連携した認証はいつか検証しないといけないと思っていました。
すこしお時間いただくと思いますが、こちらでも試していきたいと思います。

(パターン 2 の方が、ソースコード変更しなくても済むので、そちらがいまのところ有力です。)

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
早速のご返信、ありがとうございます
サポートのケースIDは「171048571001263」になります

私の方もパターン2の方で検証を進めさせていただきたいと思います
結果は後ほど共有させていただきます

引き続きよろしくお願い申し上げます

**Comment by Sugi275** [comment]
@tetuya-iyell 
Google Workspace と SAML 連携を行うための Document を作成しました。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/SAML_WITH_GOOGLE_WORKSPACE.md

自分一時的に持っている Free Trial (Business Standard) の環境だと、正常に連携ができました。

こちらお試しいただけますでしょうか？

ソースコードの変更は不要で、cdk.json の編集だけで連携できました。

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
齋藤です

ありがとうございます！
早速、試して共有をさせていただきます

引き続き、よろしくお願い申し上げますm(_ _)m

**Comment by tetuya-iyell** [comment]
@Sugi275 
お世話になっております
齋藤です

頂いた手順で、samlでloginすることができました！
ご教授、誠にありがとうございます

引き続き、ご指導をよろしくお願い申し上げますm(_ _)m
