### ISSUE TITLE
ダッシュボードについて

### ISSUE THREAD

**Issue by tetuya-iyell** [aws-samples/generative-ai-use-cases-jp#400]
最新版のgenerative-ai-use-cases-jp でダッシュボードを有効にしました
ダッシュボードを確認すると、プロンプトのログを確認することが出来ませんでした

プロンプトのログのインサイトを確認すると以下の通りになっておりました
```
filter @logStream = 'aws/bedrock/modelinvocations'
| filter input.inputBodyJson.prompt like /Human: .*/
| filter input.inputBodyJson.prompt not like /Human: <conversation>.*/
| fields @timestamp, input.inputBodyJson.prompt
```

上記で検索をしますと何もヒットしないのですが
```
| filter input.inputBodyJson.prompt like /Human: .*/
```
のfilterを削除すると、検索がヒットするようになります
これはfilterを削除してプロンプトのログを確認すればよいのでしょうか

ご教授をよろしくお願いします

**Comment by tbrand** [comment]
ダッシュボードが Claude 3 に未対応でしたので対応いたしました！それが原因か確実ではないですが、今一度最新でお試しいただけますでしょうか？お手数おかけします！

**Comment by tetuya-iyell** [comment]
@tbrand 
お世話になっております
ご回答ありがとうございます！
「 ダッシュボードのクエリの修正 #401 」を適用させて所、正しくプロンプトの検索ができるようになりました
ご対応、誠にありがとうございますm(_ _)m

**Comment by tbrand** [comment]
早速試していただきありがとうございます！今後ともよろしくお願いいたします！
