### ISSUE TITLE
新規チャット時に自動で会話一覧を最新化する

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#41]
新規チャットを始めた場合に、会話一覧を最新化して、現在の会話を一覧に自動追加する。
一覧に追加するタイミングで、件名の自動付与も同時に実施する。

**Comment by tbrand** [comment]
チャットを開始して、最初の predict が完了した時点で chat と messages を ddb に登録するので、その登録が完了したタイミングで件名の自動付与が走り、それが完了したら一覧更新という順番が良さそうですがどうでしょう。

**Comment by tbrand** [comment]
実際触ってみると、わざわざ更新しなくても swr が reinvalidate してくれる感はありますね。ただ上のタイミングではやってくれないかもです。

**Comment by wadabee** [comment]
SWRのデフォルトだと、画面やタブがアクティブになったタイミングで最新化する動きです。
任意のタイミングで行いたい場合は、`mutate`する必要があるがあるので、上記のタイミングで`mutate`を実行するようにしたいと思います。

**Comment by tbrand** [comment]
でもいいですし refreshInterval でもお手軽に似たようなことが可能かなとは思いました
