### ISSUE TITLE
Claude 3 Sonnet で翻訳機能を使用すると、不自然な文章が表示される

### ISSUE THREAD

**Issue by toshikwa** [aws-samples/generative-ai-use-cases-jp#412]
以下のように、出力末尾に追加コンテキストに関する不自然な文章が表示される。

![Screenshot 2024-03-19 at 12 43 27](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/37267851/ef779098-6dce-4fc1-9a0c-d56c8b5450a9)

**Comment by kazuhitogo** [comment]
対応完了しました！
