### ISSUE TITLE
[質問] Windowsでのローカル環境構築手順について

### ISSUE THREAD

**Issue by ahirotomi** [aws-samples/generative-ai-use-cases-jp#420]
お世話になります!

↓こちらのWindowsでのローカル環境構築手順について質問させてください。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/docs/DEVELOPMENT.md#%E3%81%9D%E3%81%AE%E4%BB%96%E3%81%AE%E3%83%A6%E3%83%BC%E3%82%B6%E3%83%BC-windows-%E7%AD%89

↓これらの記述は、どのファイルに設定するのが正解でしょうか？?

```
export VITE_APP_API_ENDPOINT=<API Endpoint>
export VITE_APP_REGION=<デプロイしたリージョン>
・・・
```

ご回答いただけるとありがたいです。
どうぞよろしくお願い致します。

**Comment by wadabee** [comment]
ご質問ありがとうございます！
手元にWindowsがなくて試せないのですが、`.env`ファイルを利用することで設定できると思われます。
https://vitejs.dev/guide/env-and-mode#env-files

`/packages/web/.env`ファイルを作成していただき、以下のように設定して`npm run web:dev`で実行することで自動で環境変数を設定されます。
```bash
VITE_APP_API_ENDPOINT=<API Endpoint>
VITE_APP_REGION=<デプロイしたリージョン>
...
```
ご確認をお願いいたします！

**Comment by ahirotomi** [comment]
ご回答いただきどうもありがとうございます！！
.envファイルに設定することで、正しく動作することを確認しましたー。
