### ISSUE TITLE
[要望] 中断ボタンの追加

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#428]
プロンプト入力途中で間違ってEnterキーを押してしまうことがあるため、
中断（キャンセル）ボタンのようなものを付けて頂けると幸いです。

![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/95996519/b0704e7e-f8fa-42dd-a44f-787d57f548e8)

**Comment by okamoto-aws** [comment]
ご要望ありがとうございます。誤ってプロンプトを送信してしまった場合は、返答を待たずにブラウザを更新いただくことで、送信内容を破棄して作業ご継続いただけると思いますが、その方法ではご要件を満たせないでしょうか？ご検討いただけますと幸いです。

**Comment by xtc-izou** [comment]
いけますね！ブラウザ更新で回避できることを知りませんでした。
ご教示頂いた方法で回避するようにします！ありがとうございました！

**Comment by xtc-izou** [comment]
回避策判明のため、Close
