### ISSUE TITLE
「最初からやり直す」でDDBのメッセージを削除

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#43]
DDBに保存されたメッセージを削除する機能を追加

**Comment by tbrand** [comment]
最初からやり直すで削除までしちゃうのはミスリーディングだと思うので、ChatGPT のようにタイトルを編集可能にして、削除ボタンも追加するのが良いと思いましたがどうでしょう。

**Comment by wadabee** [comment]
会話の削除のIssueも挙げていたのですが、会話の削除と「最初からやり直す」が完全に競合しちゃってますね。。
削除できればいいと思うので、こちらのIssueはクローズします！

**Comment by tbrand** [comment]
ありがとうございます！引き続きバンバンアイデア追加していただけると助かります！:pray:
