### ISSUE TITLE
プロンプトのテンプレート保存機能

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#46]
プロンプトのテンプレートを保存する機能。
ユースケース集という目的からは若干ズレるかもしれない

**Comment by tbrand** [comment]
どういうものをイメージされているかわからなかったので、もう少し具体的に教えていただけますでしょか？:pray:

**Comment by wadabee** [comment]
ユーザごとによく利用するプロンプトを保存する機能です。
「文書要約」とか「英文校正」などの日常的に使うプロンプトを保存するイメージです。
