### ISSUE TITLE
【機能追加要望】cdkの設定値を開発環境、ステージング環境や本番環境で切り替えたい

### ISSUE THREAD

**Issue by danishi** [aws-samples/generative-ai-use-cases-jp#462]
素晴らしいOSSプロダクトをありがとうございます。

こちらのテンプレートで作成したサイトを運用するにあたってAWSアカウントを切り替えて環境を分けているのですが、開発環境ではコスト削減のためにKendraを利用しない構成にするなど、`cdk.json`の`context`を環境ごとに切り替えてデプロイできるようにしたいです。

ご検討ください🙇‍♂️

**Comment by kazuhitogo** [comment]
ご提案ありがとうございます。
Dev/Stage/Prod で分けたいというのはよくあるご要望かつ内部でもよく議論になるのですが、利用者によって Dev/Stage/Prod の使い方が違い過ぎるため(例えば Dev １つ取ってもおっしゃっているように Kendra を使わないパターンもあれば、Developer Edition で使って Prod で Enterprise Edition にしたい、など）、このリポジトリ内でそれを表現しようとするとパターンの網羅でコードが複雑に爆発してしまう、という問題があります。（あとは dev/stage/prodでアカウントが違う場合は Profile も変えないと…などといったケースもあり）
ですので、現実解は利用者の皆様での個別最適だと考えています。
例えば、 `開発環境ではコスト削減のためにKendraを利用しない構成` であれば、`npm run cdk:deploy -- -c env=dev` のようにデプロイして、コード内で `env = app.node.tryGetContext("env")` のように引数を受け取れるので、あとは Kendra の Stack を `env=='dev'` の場合は作らない、といった分岐処理で対応がある程度可能かと思います。

**Comment by danishi** [comment]
丁寧にご説明いただきありがとうございますmm
理解、納得いたしました！独自に分岐処理を作り込もうと思います。
