### ISSUE TITLE
.gitignore の対象を追加

### ISSUE THREAD

**Issue by kazuhitogo** [aws-samples/generative-ai-use-cases-jp#476]
extension をビルドすると以下が Untracked files に出てきたため、追加する。

```
Untracked files:
  (use "git add <file>..." to include in what will be committed)
        browser-extension/dist.zip
```

**Comment by kazuhitogo** [comment]
どのタイミングかわからないですが、 `packages/cdk/cdk.context.json` も Untracked files に出ている

**Comment by tbrand** [comment]
cdk.context.json はドメインの設定をすると出ると思いますね。難しいのが、このファイル自体はコミットした方が一般的には良いのですが、このリポジトリのように汎用的なリポジトリにはコミットしちゃいけないんですよね。なので現状「このリポジトリにはコミットしないが .gitignore には入れない」という状態になっています

**Comment by kazuhitogo** [comment]
なるほど、デプロイした側はコミットしたほうがいいんですね。ここは扱いが難しい(.gitignoreに登録しちゃうとデプロイ側が.gitignore側が解除しないといけなくなる）ってことですね。どうにもならなさそうなので、Closeしちゃいます。
