### ISSUE TITLE
ファイルアップロード・音声認識からユースケースに「送る」ボタン

### ISSUE THREAD

**Issue by okamoto-aws** [aws-samples/generative-ai-use-cases-jp#486]
クエリパラメータ機能(#325)で、認識結果をワンクリックでユースケースに送れるとちょっと嬉しい気がする

**Comment by xtc-izou** [comment]
めちゃくちゃその機能欲しいです！！！！

**Comment by ttrdthsffr** [comment]
私も欲しいです。

**Comment by tbrand** [comment]
ご要望いただいた機能実装しました！思った感じと違うなど、フィードバックあればください！一旦 close させていただきます！

**Comment by ttrdthsffr** [comment]
@tbrand 様
早速ご対応いただきありがとうございました！ 使わせていただきます。

**Comment by xtc-izou** [comment]
@tbrand 
ありがとうございます！！！ #472 と #376 も類似内容ですので、Closeで結構です！
