### ISSUE TITLE
「保存したシステムコンテキスト」を選択したときに、「プロンプト例」を選択したときと同様にチャット画面に遷移したい

### ISSUE THREAD

**Issue by okamoto-aws** [aws-samples/generative-ai-use-cases-jp#489]
「保存したシステムコンテキスト」と「プロンプト例」で動作が異なる。
「保存したシステムコンテキスト」の場合は、選択後に自分でプロンプト例ペインを閉じないとプロンプトの編集に移れず、一手クリックが多くなるため、
「プロンプト例」側にあわせたほうが良さそう。

**Comment by tbrand** [comment]
ありがとうございます！概ね賛成なのですが、今は削除ボタンを出すためにそうなっているのですよね。プロンプト例に合わせたとして、削除はどのように行う想定でしょうか？前にフォーカスした時にゴミ箱アイコンが出れば良いかと思ったりもしたのですが、それだとスマホユーザーがきついかなと思ったり。

**Comment by okamoto-aws** [comment]
おぉーなるほど。
削除ボタンはそのままで、クリック時の動作だけ変えるのは無理っぽい感じでしょうか？👀
(ちなみに今ためしに初めて削除ボタン押してみたんですが、「削除していいですか？」という確認が出ると思いきや、即消えてちょっと焦りましたｗ)

**Comment by tbrand** [comment]
技術的に可能かというと easy なのですが、UX 的に良いかと言うと微妙だと思います。
すぐに右の drawer を閉じちゃうと削除ボタンがあるのに気づくのが難しいと思いますし、また今後タイトルも変更可能にする予定なのですよね。(会話履歴のタイトルを変更できるのと同じ感じ)

**Comment by okamoto-aws** [comment]
あ、理解しました。クリックしたときだけ削除ボタンが出るんですね。
「保存したシステムコンテキスト」に編集ボタンを一つ常に表示しておいて、そこをクリックするとすべてのカスタムシステムコンテキストに編集・削除ボタンが出現するUXだと難しいのでしょうか？画面が少しbuzyになりますが

**Comment by tbrand** [comment]
それはありだと思います！システムコンテキスト編集のタスク誰かがとった時にこちらの Issue 貼ってもらえます？
