### ISSUE TITLE
ファイルアップロード機能において、アップロード（認識）エラーとなる形式がある

### ISSUE THREAD

**Issue by ttrdthsffr** [aws-samples/generative-ai-use-cases-jp#497]
ファイルアップロード機能ですが、認識エラーとなるファイル形式が存在するようです。
ご確認いただけますと幸いです。

■アップできない（エラー発生）
　csv  
　doc 
　docx 
　ppt  
　tsv  
 
■アップできてファイル認識結果が表示される
　md  
　pdf  
　pptx 
　xlsx 

※アップできない場合は、以下のエラーが発生しております。
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/166420369/a5af6469-16ff-480d-87d9-50f79b2bf987)

**Comment by kazuhitogo** [comment]
手元の環境だと、表示がおかしくなってはいるのですが（これはこれで問題ですが）、csv のアップロードには成功するようです。
もし失敗するファイル等をいただけるのであればいただくことは可能でしょうか？
<img width="1463" alt="image" src="https://github.com/aws-samples/generative-ai-use-cases-jp/assets/7238979/8857da9b-c4be-4266-af43-a45c7b5ebe35">

**Comment by ttrdthsffr** [comment]
暫く回答できておらず申し訳ございません。
ファイルアップロード機能 Deprecated (完全廃止予定 2024/09 末)と伺いましたので、本Issueはクローズさせていただきます。
ありがとうございました。
