### ISSUE TITLE
Guardrail の追加

### ISSUE THREAD

**Issue by kazuhitogo** [aws-samples/generative-ai-use-cases-jp#499]
Bedrock の Guardrail をかぶせる機能をオプションでつけたい

**Comment by tanuk9** [comment]
この GenU をきっかけに、 AWSで世界中で使用する生成AI基盤を構築する予定です。
このガードレールはぜひ対応させて、経営層に統制していることをアピールしたいです。

https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/bedrock-runtime/command/ApplyGuardrailCommand/
こちらをベースに bedrockApi.ts を改造しましたが、
「INFO	ValidationException: Guardrail was enabled but input is in incorrect format.」
と出てしまいます。

ぜひ実装のご検討をお願いいたします。

**Comment by kazuhitogo** [comment]
@tanuk9 
こちらの PR で対応しました！ご確認ください。
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/608

**Comment by tanuk9** [comment]
@kazuhitogo 
ご対応いただきありがとうございます！
guardrail.ts に追記しデプロイしてみます！
