### ISSUE TITLE
コードブロックが生成された際に１行が長すぎると見切れてしまう

### ISSUE THREAD

**Issue by tsukumonasu** [aws-samples/generative-ai-use-cases-jp#536]
コードブロックが生成された際に１行が長すぎると見切れてしまい、横スクロールも表示されないため、コピーできない。

**例**
AWS CLI
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/9390079/bc21ae5c-f4a8-4a6a-bd20-e98328822a37)

画像生成プロンプト
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/9390079/e06cf09a-60db-46bc-9357-3bd327c98992)

**Comment by tsukumonasu** [comment]
再現プロンプト例
AWS　CLIでS3にファイルをアップロードするのにすべてパラメータを使うコマンド教えて、１行で分けずにコマンドブロックを生成して
![image](https://github.com/aws-samples/generative-ai-use-cases-jp/assets/9390079/b31fa6f3-0905-4cb6-9c03-75ba61ffd785)

**Comment by tbrand** [comment]
遅くなり申し訳ございません。こちら対応いたしました。

**Comment by tsukumonasu** [comment]
@tbrand 
ご対応ありがとうございます。
スクロールできるようになったことが確認できました。
![Uploading image.png…]()
