### ISSUE TITLE
dashboardを有効化した状態でmodelRegionを変更するとデプロイに失敗する

### ISSUE THREAD

**Issue by okamoto-aws** [aws-samples/generative-ai-use-cases-jp#554]
crossRegionReferencesが原因と思われる。
対応案
- modelRegion切替時の手順(一度ダッシュボードを無効化)をDocumentに記載する
- なにか技術的な解決策

**Comment by tbrand** [comment]
ドキュメントに追記したため、クローズします。
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/612
