### ISSUE TITLE
【改善要望】CloudFormationでのRAG チャット機能はデフォルトはfalseにしてほしい。

### ISSUE THREAD

**Issue by hide-G** [aws-samples/generative-ai-use-cases-jp#568]
![image](https://github.com/user-attachments/assets/e4e2a4d8-c185-4365-87e9-4e55af612760)
「RAG チャット機能を有効化する場合は、RagEnabled を true に変更します。有効化しない場合は false のままとします。」
と記載いただいています。
しかしながらポチポチと進めてしまうと、高額なAmazon Kendraを使ったRAGが設定されてしまうそうなので、デフォルトは無効(false)に出来れば、初学者の悲しい課金が減らせるのではと思いました。ご検討の程、宜しくお願いします。

![image](https://github.com/user-attachments/assets/77e112d2-feb5-4d74-9446-fc0f431bd8f0)

**Comment by toshikwa** [comment]
@hide-G
feedback ありがとうございます！

元々 GitHub リポジトリとは独立した「ワークショップ用のコンテンツ」として CloudFormation テンプレートを用意していたものの、そのまま継続的にご利用いただいている方も非常に多い状況を考慮して、「RagEnabled をデフォルトで false とする」形で対応させていただければと思います。

来週前半を目処に対応できればと思っておりますので、しばしお待ちいただけますと幸いです。
改めて、貴重な feedback ありがとうございました。

**Comment by toshikwa** [comment]
@hide-G
お世話になっております。予定より遅くなってしまいましたが、「RagEnabled をデフォルトで false とする」対応が完了いたしました。CDK での Knowledge Bases for Amazon Bedrock を使用した手順も追加しておりますので、より開発・検証におけるコストを抑えたい場合などにご活用いただけますと幸いです。

改めて、ありがとうございました！

**Comment by hide-G** [comment]
ご対応ありがとうございます。
CloudFormationでfalseにご対応いただいたのは確認できました。作成と削除とも確認できました。

**Comment by hide-G** [comment]
※　こちら、私の入力ミスなのか、まだはっきり切り分け出来ていないので別にしました。不適切であれば後日削除します。

CDK でのデプロイですが、SageMaker Studio のCode Editorが固まって、CodeEditorStackの作成し直しを試すと、「ROLLBACK_COMPLETE」になりました。
「SageMaker Studio Lifecycle Configs」などを別途削除する事で、CloudFormationのCodeEditorStackを実行し直しに出来ました。

その後、『2-b.5. AWS へのデプロイ』まで進めたのですが、次の新しいエラーが出てしまい、確認ができない状況です。

Deployment failed: Error: RagKnowledgeBaseStack: SSM parameter /cdk-bootstrap/hnb659fds/version not found. Has the environment been bootstrapped? Please run 'cdk bootstrap' (see https://docs.aws.amazon.com/cdk/latest/guide/bootstrapping.html)
    at Deployments.validateBootstrapStackVersion (/home/sagemaker-user/generative-ai-use-cases-jp/node_modules/aws-cdk/lib/index.js:453:12210)

**Comment by toshikwa** [comment]
@hide-G 
feedback ありがとうございます！

ワークショップで利用している Code Editor の CloudFormation テンプレートには、「一定時間ファイル更新のアクティビティが検出されない場合に Code Editor Space を自動停止する」機能を追加実装しています。「Code Editor Space が自動で停止した」ことが「固まった」原因の場合、SageMaker Studio から再度 Space を起動することで解消するかと思います。この機能は、`AutoStopIdleTimeInMinutes` パラメーターを `0` に設定してスタックを作成することで無効化できます。

また Code Editor の CloudFormation テンプレートについて、Studio Lifecycle Config が削除されないバグがあることを確認しました。このバグを修正、各リソースの名前に一意な suffix を付与する対応を実施し、テンプレートを更新しました。Code Editor に関して、上記の対応で問題が解決しない場合、お手数ですが改めて共有いただけますと幸いです。

またデプロイ失敗の件ですが、下記コマンドを実行した上、改めてデプロイを実施してみていただけますでしょうか？
(手順に記載漏れがありました。大変失礼しました。)
```bash
cd ~/generative-ai-use-cases-jp
npx -w packages/cdk cdk bootstrap
```

手順・テンプレートに不備があり、大変ご迷惑をおかけしました。貴重なフィードバック、本当にありがとうございます。
