### ISSUE TITLE
RAG チャット (Knowledge Base) でうまく回答できない質問

### ISSUE THREAD

**Issue by tak-ickw** [aws-samples/generative-ai-use-cases-jp#580]
RAG チャット(Knowledge Base)に関しまして、設定で有効化、ドキュメントを投入して Sync したのですが、
うまく質問に回答できないケースがあります。
（うまく回答できないパターンは複数回質問しても失敗します。）

同様の質問をマネジメントコンソールから直接 KnowledgeBase に投げると、
S3に格納したドキュメント内から回答してくれるので、Embedding は成功しているように見えます。

添付の Excel にサンプルを貼り付けました。
[RAGチャットの回答が失敗するサンプル.xlsx](https://github.com/user-attachments/files/16408586/RAG.xlsx)

よろしくお願いいたします。

**Comment by tbrand** [comment]
シェアありがとうございます。こちらブラウザの開発者モードから retrieve api を呼び出した時に結果が返ってきているか確認していただくことは可能でしょうか？

**Comment by tak-ickw** [comment]
ご回答ありがとうございます。RAGチャットを一旦無効化したのですが、再度有効化してデプロイしたところRAGチャットが動作しなくなってしまったため少しおまち頂けますでしょうか。

**Comment by tak-ickw** [comment]
コスト削減のため、一旦RAGチャットを無効化していたのですが、こちらの確認のため再度有効化しようとしているのですが、RAGチャットが使用できない状態です。
![image](https://github.com/user-attachments/assets/dc12ded9-d504-464b-8b91-f43d6cbaaf59)

OpenSearch のコレクションが作成されていないないため、それが原因だと思われるのですが、解決方法分かりますでしょうか。

以下の手順で無効化→有効化を行いました。

1. RAGチャット無効化
"ragKnowledgeBaseEnabled": false
にしてデプロイ実行

2. コレクション削除
コスト削減のため OpenSearch のコレクションを削除

3. 再度有効化
"ragKnowledgeBaseEnabled": true
にしてデプロイ実行
→ OpenSearchのコレクションが作成されない

**Comment by tbrand** [comment]
こちら回答済みだと思いますので、一旦 close させていただきます。よろしくお願いいたします。
