### ISSUE TITLE
【仕様確認】Knowledge BaseでのRAGでの確認

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#584]
現状、GenUでRAGを実装する方法として、
1. KendraとClaudeの組み合わせ
2. Knowledge BaseとClaudeの組み合わせ
があると思います（下図より）。
![image](https://github.com/user-attachments/assets/606babbb-ea63-428a-aac8-c49b96ab6bb3)

Knowledge BaseとClaudeの組み合わせでは、「**OpenSearch ServerlessをKendraの代わりにキーワード検索、
セマンティック検索**」の代替機能として利用することは可能でしょうか？
それともKnowledge BaseとClaudeの組み合わせでのKnowledge Baseは単にベクトルDBとClaudeの組み合わせになるのでしょうか？

Kendraの代わりにOpenSearch Serverlessを全文検索サービスとして利用できないか、という検討を行っています。

**Comment by tbrand** [comment]
Knowledge Base は現状ハイブリッドサーチ (キーワード + ベクトル) で実装されています。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/cdk/lambda/retrieveKnowledgeBase.ts#L39
こちらの [overrideSearchType](https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent-runtime_KnowledgeBaseVectorSearchConfiguration.html#bedrock-Type-agent-runtime_KnowledgeBaseVectorSearchConfiguration-overrideSearchType) は 'HYBRID' (キーワード + ベクトル) か 'SEMANTIC' (ベクトル) のみが選択可能ですので、純粋なキーワード検索のみの要件で Knowledge Base を使うことが現状できません。
よろしくお願いいたします。

**Comment by xtc-izou** [comment]
@tbrand 
HYBRIDタイプでKendraを代替できるか試してみる価値ありそうですね！

**Comment by tbrand** [comment]
こちら一旦クローズさせていただきます。
