### ISSUE TITLE
[機能要望]翻訳結果の音声出力(発音確認用)

### ISSUE THREAD

**Issue by YamashitaShoji** [aws-samples/generative-ai-use-cases-jp#596]
GenU活用させていただいています。ありがとうございます。
翻訳機能を便利に利用していますが、発音が分からないケースにて、別サイトを利用しないといけません。
Amazon Pollyを利用して、発音機能を追加できますでしょうか。
(一般的な翻訳サービスについている音声出力マークボタンをイメージしています)

ご検討よろしくお願いいたします。

**Comment by tbrand** [comment]
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/605
Polly を追加しました！ご要望ありがとうございます。

**Comment by YamashitaShoji** [comment]
ありがとうございます！！！

**Comment by tsukumonasu** [comment]
実装ありがとうございます。
早速、マージしてデプロイさせていただきました。

弊社で外国語を使うチームに聞いてみましたが、喜んでおりました。
要望としては、中国語も欲しいという声がありました。

**Comment by tbrand** [comment]
ありがとうございます！こちらの Issue 自体は一旦 close させていただきます！引き続き多言語対応を進めてまいります
