### ISSUE TITLE
【改善要望】RAGチャットにおいて、2回目以降の会話の根拠文書の紐づけがおかしくなることがある

### ISSUE THREAD

**Issue by ttrdthsffr** [aws-samples/generative-ai-use-cases-jp#601]
RAGチャットにおいて、連続で会話を進めると、2回目以降の会話の根拠文書の紐づけがおかしくなることがあります。
回答内容は正しいのですが、根拠となるファイルリンクが異なっている状態です。

例）
![image](https://github.com/user-attachments/assets/52050922-c400-4ae2-a7e2-52ff3f207299)

⇒製品Bの内容はB.txtに記載されているはずが、D.txtがリンクとして表示される

[使用したファイル.zip](https://github.com/user-attachments/files/16570354/default.zip)

※上記は解析のためファイル内容と会話を単純化しておりますが、
　実際に業務上のファイルを多数アップした状態でRAGチャットを行った場合も、同様の現象が発生しております。
　なお、この現象は1回目の会話では発生しません。

**Comment by Kubota-Yoshiharu** [comment]
全く同じ事象が私の環境でも発生しました。
RAGはKnowledge Base版です。

**Comment by ttrdthsffr** [comment]
コメントありがとうございます。こちらでもKnowledge Base版でも発生いたしました。
本件、原因判明して改修できましたので、別途対応を投入いたします。

**Comment by ttrdthsffr** [comment]
対応投入しましたのでクローズします。
