### ISSUE TITLE
【改善要望】同じスレッドでチャットを続けると、文字描画とキーボード入力が徐々に遅くなっていく

### ISSUE THREAD

**Issue by ttrdthsffr** [aws-samples/generative-ai-use-cases-jp#604]
同じスレッドでチャットを続けますと、文字描画とキーボード入力が徐々に遅くなっていきます。

（参考動画）
https://public-bucket-temp.s3.us-west-2.amazonaws.com/GenU_%E3%81%A0%E3%82%93%E3%81%A0%E3%82%93%E9%81%85%E3%81%8F%E3%81%AA%E3%82%8B.mp4

**Comment by tbrand** [comment]
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/606
入力が遅くなる問題についてはこちらで対応しましたので、確認していただくことは可能でしょうか？
また、出力に関しても一部の遅延についてはこちらの対応で緩和された認識です。ただし、出力がスタックする問題があり、そちらは別に原因があるため対応中です。

**Comment by tbrand** [comment]
こちら一旦クローズさせていただき、出力がスタックする問題は別の Issue として切り出させていただきます。

**Comment by ttrdthsffr** [comment]
@tbrand 
返答遅くなり申し訳ございません。改善されていることを確認しました。ありがとうございました。
