### ISSUE TITLE
新規会話開始時にDrawerの会話履歴を選択状態にする

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#62]
新規会話を開始して会話履歴に会話が追加されたら、その新規追加された会話を選択状態にする
現在は、PathParamsと一致しているかで選択状態を判断しているため、そこの実装を変える必要がある

* 選択状態を保持するStateを別途用意する
* 新規会話を登録して、ChatIDが取得できたタイミングでリダイレクトする（画面ちらつきの原因になりそうなのでできればやりたくない）

**Comment by tbrand** [comment]
こちらは 2 重管理の観点から会話履歴に飛ぶとチャットの方はリセットするように変更したので、クローズします。
