### ISSUE TITLE
翻訳結果の音声出力多言語対応

### ISSUE THREAD

**Issue by tbrand** [aws-samples/generative-ai-use-cases-jp#631]
https://github.com/aws-samples/generative-ai-use-cases-jp/issues/596

**Comment by tbrand** [comment]
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/638

**Comment by tbrand** [comment]
対応完了

**Comment by tsukumonasu** [comment]
@tbrand 
多言語対応ありがとうございます。
中国語だけでなく、様々な言語への対応していただけるとは思っていなかっただけに
非常に嬉しく思います。
弊社の社内掲示板でも共有させていただきます。
