### ISSUE TITLE
【要望】クロスリージョン推論対応

### ISSUE THREAD

**Issue by xtc-izou** [aws-samples/generative-ai-use-cases-jp#647]
本番環境でこちらの対応があると安心できます。
https://aws.amazon.com/jp/blogs/machine-learning/getting-started-with-cross-region-inference-in-amazon-bedrock/

**Comment by kazuhitogo** [comment]
https://github.com/aws-samples/generative-ai-use-cases-jp/pull/626
こちらの Pull Request にて対応済です(マージ済)

**Comment by xtc-izou** [comment]
ありがとうございます！

**Comment by xtc-izou** [comment]
対応済みとのことで、Closeします。
