### ISSUE TITLE
Bad ボタンの充実

### ISSUE THREAD

**Issue by kazuhitogo** [aws-samples/generative-ai-use-cases-jp#655]
Good/Bad ボタンの実装は済んでいるが、Bad を押したとて、何が Bad だったのかを残すことができないので、何が悪かったのかを記述できるような機能が欲しい

**Comment by aoranow-yoshi** [comment]
<Vertex AI>
![image](https://github.com/user-attachments/assets/87d90511-0546-41f1-820b-c4a7151a8908)

<Gemini Advanced>
![image](https://github.com/user-attachments/assets/4382a762-fcf4-4d12-b6d0-e70cc59423a6)

ご参考になりそうな例を添付させていただきます。
