### ISSUE TITLE
ip制限のミス？

### ISSUE THREAD

**Issue by ha-to11** [aws-samples/generative-ai-use-cases-jp#678]
common-web-acl.tsにある
if (hasAllowedIpV6) {
      const wafIPv6Set = new CfnIPSet(this, `IPv6Set${id}`, {
        ipAddressVersion: 'IPV6',
        scope: props.scope,
        addresses: props.allowedIpV4AddressRanges ?? [],
      });
でipv4が指定されている？
合っていたらすみません。。。

**Comment by tbrand** [comment]
ご報告ありがとうございます。大変失礼いたしました。こちら修正いたしました。
