### ISSUE TITLE
サーバーアクセスのログ記録の設定元と設定先のS3バケットが同一になっている

### ISSUE THREAD

**Issue by yusuke-takikawa-s** [aws-samples/generative-ai-use-cases-jp#681]
本ツールにてデプロイされるS3バケット「ragknowledgebasestack-datasourcebucket（省略）」ですが、サーバーアクセスのログ記録設定で同バケットを指定しているようです。
その影響か、同バケットにログと見られる大量のオブジェクトが蓄積していたため、イシューを起票させていただいた次第です。
ご確認の程、よろしくお願いいたします。

## 参考情報
- https://repost.aws/ja/knowledge-center/s3-server-access-logs-same-bucket
- https://zenn.dev/snaka/articles/128710d7974d5b

**Comment by tbrand** [comment]
ご報告ありがとうございました！
