### ISSUE TITLE
【要望】Knowledge Base を使用した場合に発生するコストについて

### ISSUE THREAD

**Issue by Kubota-Yoshiharu** [aws-samples/generative-ai-use-cases-jp#682]
https://catalog.workshops.aws/generative-ai-use-cases-jp/ja-JP/overview/cost
のページに
`RAG チャット機能を有効化しない場合`
`RAG チャット機能 (Kendra) を有効化する場合`
の料金試算例がありますが、
ここに
`RAG チャット機能 (Knowledge Base) を有効化する場合`
の料金試算例も追加頂けると非常に助かります。

以上、ご検討の程宜しくお願い致します。

**Comment by sugusugiaws** [comment]
フィードバック、ありがとうございます。追加する予定はあります。一方、公開するタイミングに関して制限もあり、今すぐ、というわけではない点の共有です。

**Comment by toshikwa** [comment]
feedback ありがとうございます！ ワークショップにも反映させていただきました 🙏
https://catalog.workshops.aws/generative-ai-use-cases-jp/ja-JP/overview/cost
