### ISSUE TITLE
【要望】翻訳ページ音声出力のiOSデバイス対応

### ISSUE THREAD

**Issue by SizeOn-Matty** [aws-samples/generative-ai-use-cases-jp#685]
関連：音声出力多言語対応 #638

当該機能、非常に便利に使わせていただいてます。
ありがとうございます。

リアルタイムで会話を拾って、機械音声で通訳させる機能について
iPhoneなどのモバイルデバイスをマイクのように活用し、通訳機のように使いたいのですが、
現状iOSの「iOS版Safari」「iOS版Chrome」「iOS版Edge」どのブラウザで開いても音声再生ができないようです。

こちらの対応が可能でしたらよろしくお願いいたします。

**Comment by wadabee** [comment]
こちら自分の手元の環境で試してみましたところ、問題なく音声再生できました。

> iPhone 14 Pro
iOS 18.0.1

お使いのデバイスは、個人所有の何も制限がかかっていないものでしょうか？

**Comment by SizeOn-Matty** [comment]
@wadabee 様

ご返信ありがとうございます。
MDMやプロファイルなど入っていない無制限の
・iPhone13（iOS　17.6.1）
・iPhone14（iOS　17.6.1）
で試行しておりました。

改めてiOS18に更新してみたいと思います。

**Comment by SizeOn-Matty** [comment]
@wadabee 様

結論から、
iOS18.0.1に更新したことで、iPhone13/14いずれのブラウザからも機械音声の再生ができるようになりました。
iOS17の友人に施行させたところ、私と同様の症状だったためIOS18以降が推奨の機能と認識しました。

アドバイスありがとうございました。
解決したため、クローズさせていただきます。

**Comment by wadabee** [comment]
ご確認とご報告ありがとうございます。
iOSのバージョンで社外製ブラウザの挙動が変わる場合もあるんですね。。。
とても参考になりました。ありがとうございました。
