### ISSUE TITLE
ファイルアップロード機能について

### ISSUE THREAD

**Issue by ha-to11** [aws-samples/generative-ai-use-cases-jp#686]
いくつかご質問あるのですが
①ファイルアップロード機能が削除された理由ってどこか記載がありますか？
②それに伴って、ユースケースのチャットの方でもファイルをLLMに送信できなくなってますか？

**Comment by tbrand** [comment]
1. 削除された理由はチャットやその他の一部のユースケースでファイルアップロードが可能になったためです。ただし、一部のファイルフォーマットがまだサポートできていません。
2. できると思いますが、何らかのエラーが発生しますでしょうか？

**Comment by ha-to11** [comment]
こちら社内のブラウザ環境のせいと分かりました。
edgeだとファイルアップロードが効かず、Chromeだと可能でした。
