### ISSUE TITLE
チャットの先頭に戻る、最下位に進むボタンの設置要望

### ISSUE THREAD

**Issue by ttrdthsffr** [aws-samples/generative-ai-use-cases-jp#695]
**背景**
チャット機能で長文で継続的にラリーする場合、スクロールバーが小さくなって、
最下位に持っていったり、先頭に戻ったりするのが煩わしいです。

**追加要望**
先頭に戻る、最下位に進むボタンを設置いただくことはできませんでしょうか。

**Comment by tbrand** [comment]
こちら実装完了しております。https://github.com/aws-samples/generative-ai-use-cases-jp/pull/706

**Comment by ttrdthsffr** [comment]
@tbrand 
ご対応いただきありがとうございました。
