### ISSUE TITLE
Claude 3.5 v2 (Sonnet/Haiku)でKendra Ragを行うと高確率でPredictがNo Queryとなってしまう

### ISSUE THREAD

**Issue by n-guitar** [aws-samples/generative-ai-use-cases-jp#716]
**バグの説明**
Claude 3.5 v2 (Sonnet/Haiku)でKendra Ragを行うと高確率でPredictがNo Queryとなり、正しくRagが出来ません。

**再現手順**
その振る舞いを再現する手順:
1. 生成 AI 体験ワークショップ に従いKendraをデプロイ
https://catalog.workshops.aws/generative-ai-use-cases-jp/ja-JP

2. 生成 AI 体験ワークショップ に従いKendraのデータを準備
https://catalog.workshops.aws/generative-ai-use-cases-jp/ja-JP/add-data/kendra
kintai.pdf (勤怠管理システム入力方法マニュアル)をS3にuploadし、Kendraで同期

3. Ragチャットページ(/rag)でRagを実行
例：
社内Wifiの使用方法を教えて
USBメモリを使用するにはどうしたらいいですか？
勤怠システムのURLは？

4. Browserの開発者モードでNetworkのpredictの値を参照

**想定される動作**
No Queryではなく、正しいQueryに変換され、Kendraの結果を出力できる。

**スクリーンショット**
問題を説明するのに役立つ場合は、スクリーンショットを追加してください
<img width="1305" alt="image" src="https://github.com/user-attachments/assets/a2226cb7-7a66-4170-b722-8ea1a3dcccec">
<img width="966" alt="image" src="https://github.com/user-attachments/assets/2ee2593d-0b45-4b10-bd66-b076ee5e001a">

**Comment by Hasebet** [comment]
私自身初の書き込みのため、ルールがありましたらご指摘ください。

クエリ生成文の167行目にある
* 「要約して」などの質問ではないQueryは全て無視してください
がClaude 3.5 v2 (Sonnet/Haiku)では正しい意味に捉えられていないかもしれません。
私の場合はここを
* 質問ではないQueryは全て無視してください。無視する例：「要約して」,「翻訳して」,「計算して」
としたところ、正常に動作しました。
[https://github.com/aws-samples/generative-ai-use-cases-jp/blob/main/packages/web/src/prompts/claude.ts](url)

**Comment by tbrand** [comment]
こちらご意見いただきありがとうございました！そちらのプロンプトを反映させていただきました。
こちらは close させていただきます。
引き続きよろしくお願いいたします。
