### ISSUE TITLE
[ユースケースビルダー]Knowledge Baseへの対応

### ISSUE THREAD

**Issue by okamoto-aws** [aws-samples/generative-ai-use-cases-jp#733]
**機能リクエストは何か問題に関連していますか？背景を説明してください**
現状、普通のLLMしか出力先に設定できない。

**追加 or 改善したい機能について**
Knowledge Baseの指定をできるようにし、データソースに基づいた推論を行うカスタムユースケースの作成を可能にする。

**Comment by tbrand** [comment]
これ分解しても良いですか？KB と Agent は分けた方が良い気がします。

**Comment by okamoto-aws** [comment]
分割だいじょうぶです
