### ISSUE TITLE
ユースケースビルダーで作成したユースケースでは、クリアを押してもコンテキストが残る

### ISSUE THREAD

**Issue by icoxfog417** [aws-samples/generative-ai-use-cases-jp#749]
**バグの説明**
ユースケースビルダーを利用しているユーザーとして、「クリア」を押したら入力欄がクリアされるためコンテキストもクリアされて最初からやり取りを始められると感じるが、実際はテキストエリアの内容がクリアされるだけでコンテキストは残っている。

例えば、「入力テキスト」から「メール文」を作成するユースケースを作成し、一度実行した後「クリア」を押して、再度入力テキストを入力すると 2 回目の「メール文」は①前回の入力テキスト+②前回のメール文+③再度の入力テキストをコンテキストとして作成される。

**再現手順**
その振る舞いを再現する手順:
1. ユースケースビルダーに移動する
2. 適当なユースケースを作成する
3. ユースケースに入力を与え出力を得る
4. クリアボタンを押す
5. 再度ニュースケースに入力を与え出力を得る
6. ビルダーモードを中断し、会話履歴を参照すると 5 の出力が 3 の入出力を与えたうえで出されたものであることが確認できる。

**想定される動作**
クリアを押したら新規チャットとして処理される。あるいは、「最初からやり直す」という入力欄のクリアとは異なる機能を持つボタンを新設する。

(コードを見たうえでの所感)
`useChat` には `clear` 以外に [`init` が存在するが](https://github.com/aws-samples/generative-ai-use-cases-jp/blob/b8632d1dd429ca4e674ec5308a8289ead1ddd3ed/packages/web/src/hooks/useChat.ts#L510) (新規 id でチャットをやり直す?) 、ユースケースビルダーでは `clear` のみが使用される = 一度採番された id でやり取りが続くように見える。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/b8632d1dd429ca4e674ec5308a8289ead1ddd3ed/packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx#L95

**Comment by wadabee** [comment]
ご報告ありがとうございます！

本件は「クリアボタンを押さずに、手動で入力欄をクリアした場合」の事象ではないでしょうか？
手元の環境でクリアボタンの挙動を確認しましたところ、別の会話で履歴が作成されました。
少し細かい話になりますが、クリアボタンが押されたタイミングで`useChat`の`clear`を実行しており、ここで会話が初期化されます。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/b8632d1dd429ca4e674ec5308a8289ead1ddd3ed/packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx#L94
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/4b44220159552d72c5067bf71fca18ae386d5f5b/packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx#L159-L162

（Undocumentedな仕様で恐縮なのですが、）会話履歴上は会話が続いているように見えますが、`ignoreHistory=true`で`postChat`を実行しているため、会話履歴が無視され一問一答の形式で回答が生成される動きとなります。
ユースケースビルダーに限らず、標準の機能（翻訳など）もこちらの方法で実装をしています。
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/4b44220159552d72c5067bf71fca18ae386d5f5b/packages/web/src/components/useCaseBuilder/UseCaseBuilderView.tsx#L152
https://github.com/aws-samples/generative-ai-use-cases-jp/blob/4b44220159552d72c5067bf71fca18ae386d5f5b/packages/web/src/hooks/useChat.ts#L365-L369

**Comment by icoxfog417** [comment]
今確認したところ、クリアボタンを押せばリセットされることを確認しました！(お手間をかけて申し訳ない・・・)
ご確認ありがとうございます。
