### ISSUE TITLE
【要望】stability aiのimg2img機能でインプット画像から新たに画像を生成したい

### ISSUE THREAD

**Issue by cresco-naoki-yoshimura** [aws-samples/generative-ai-use-cases-jp#754]
**機能リクエストは何か問題に関連していますか？背景を説明してください**
画像生成のUI上ではテキストからイメージを生成できるケースしかなく、画像から新たな画像を生成する事ができません。

**追加 or 改善したい機能について**
画像生成のUI上でインプット画像と指示を基に新たな画像を生成したいです。
例えば、ペットの写真をインプットとして与えて「アニメ調に変更して」と指示する事で
アップした写真を編集できるような機能があれば画像生成を利用できるケースも増えるのではと考えております。
ご検討の程、宜しくお願い致します。

**Comment by okamoto-aws** [comment]
こちらすでに対応しており、詳細なパラメータのGenerationModeから、"IMAGE_VARIATION"をご選択ください。
ただし、お試しいただくとわかるかと思いますが、ご所望の既存実写画像の編集機能のような使い方は、モデルの仕組み上、比較的難易度が高いかと思います。
![image](https://github.com/user-attachments/assets/e7815dcb-68d0-4802-a40a-26466d455d1d)

**Comment by cresco-naoki-yoshimura** [comment]
既に組み込まれていたのですね。
早速、試してみようと思います。

ご返答ありがとうございました。
