### ISSUE TITLE
画像生成機能のユースケース

### ISSUE THREAD

**Issue by wadabee** [aws-samples/generative-ai-use-cases-jp#82]
BedrockでStable Diffusionを実行することができるので、それを使ったユースケース。
TranslateかLLMをかませる形にして、日本語でプロンプトを入力できる形にする。

**Comment by tbrand** [comment]
prompt に癖があるので、text-to-text で prompt をお勧めしてくれると良い.

**Comment by tbrand** [comment]
記事の生成 => 画像生成でサムネイル作成
